title: John Oerter
description: Software developer in Omaha, NE

url: http://john.oerter.us
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html

social:
   github: joerter
   twitter: joertes10
   email: john@oerter.us

google_analytics: "UA-65241399-1"
